baseurl = "https://damog.net/blog/"
languageCode = "en-us"
title = "David Moreno's blog"
theme = ["archie"]
googleAnalytics = "UA-136378273-1"
disqusShortname = "https-damog-net"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
disableHugoGeneratorInject = true
paginate = 6

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[taxonomies]
tag = "tag"

[permalinks]
    posts = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "/blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "damog.net"
    url = "https://damog.net/"
    weight = 3
[[menu.main]]
    name = "feed"
    url = "/atom.xml"

[params]
    description = "David Moreno blog"
    mode="dark"

[mediaTypes]
  [mediaTypes."application/atom"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.Atom]
    mediaType = "application/atom"
    baseName = "atom"
    isPlainText = false


[outputs]
home = [ "HTML", "RSS", "Atom" ]
taxonomy = ["HTML", "Atom"]
taxonomyTerm = ["HTML", "Atom"]

